version: "3.9"

services:
  nextcloud:
    image: ghcr.io/juliusknorr/nextcloud-dev-php83:latest
    container_name: nc31-dev
    ports:
      - "8088:80"
    environment:
      # NC-Server-Tag/Branch ausw√§hlen
      SERVER_BRANCH: v31.0.8
    volumes:
      # nur Config und Data persistent machen
      - nc31_config:/var/www/html/config
      - nc31_data:/var/www/html/data

      # dein App-Code "live" einbinden (Pfad anpassen!)
      - /home/thewestboi/Documents/dev/devCalDash/aaacalstatsdashxyz:/var/www/html/apps-extra/aaacalstatsdashxyz

    restart: unless-stopped

volumes:
  nc31_config:
  nc31_data:

