version: "3.9"

services:
  nextcloud:
    image: ghcr.io/juliusknorr/nextcloud-dev-php83:latest
    container_name: nc31-dev
    ports:
      - "8088:80"
    environment:
      # NC-Server-Tag/Branch auswählen
      SERVER_BRANCH: v31.0.8
    volumes:
      # persistenter Server + Daten (verhindert erneutes Herunterladen)
      - nc31srv2:/var/www/html
      # dein App-Code "live" einbinden (→ Pfad unten anpassen!)
      - /home/thewestboi/Documents/dev/devCalDash/aaacalstatsdashxyz:/var/www/html/apps-extra/aaacalstatsdashxyz
    restart: unless-stopped

volumes:
  nc31srv2:

